---
title: "benchmarking"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Making coverage matrices from bamfiles

```{r libraries}
library(microbenchmark)
library(GenomicWidgets)
library(genomation)
library(GenomicRanges)
```

```{r sample_info}
genomation_dir <- system.file("extdata", package = "genomationData")

samp.file <- file.path(genomation_dir,'SamplesInfo.txt')
samp.info <- read.table(samp.file, header=TRUE, sep='\t', 
                       stringsAsFactors = FALSE)
samp.info$fileName <- file.path(genomation_dir, samp.info$fileName)

```

```{r peaks}
ctcf.peaks = genomation::readBroadPeak(system.file("extdata",
                         "wgEncodeBroadHistoneH1hescCtcfStdPk.broadPeak.gz",
                         package = "genomationData"))
ctcf.peaks = ctcf.peaks[seqnames(ctcf.peaks) == "chr21"]
ctcf.peaks = ctcf.peaks[order(-ctcf.peaks$signalValue)]
ctcf.peaks = resize(ctcf.peaks, width = 1000, fix = "center")
```

```{r benchmark}
bm <- microbenchmark::microbenchmark(ctcf_mats = make_coverage_matrix(samp.info$fileName[1:3], 
                                                                ctcf.peaks, 
                                   up = 500, down = 500, 
                                   binsize = 25), 
                               geno = ScoreMatrixList(samp.info$fileName[1:3], ctcf.peaks, bin.num = 1000/25),
                               times = 5)

bm

plot(bm)
```

