---
title: "expression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# Reading in Roadmap Epigenomics Project Expression Data from AnnotationHub

This vignette describes how the expression data object included in GenomicWidgets was created.

## Reading in protein coding RPKM

```{r}
library(AnnotationHub)
library(dplyr)
ah = AnnotationHub()
expr_data <- query(ah , c("EpigenomeRoadMap", "RPKM"))
rpkm_pc = expr_data[["AH49019"]]
```

## read in metadata

```{r}
meta_data <- query(ah , c("EpigenomeRoadMap", "metadata"))[["AH41830"]]
```

## Get genes on chr21

```{r}
library(Homo.sapiens)
entrez_mapping <- AnnotationDbi::select(Homo.sapiens, 
                                        rownames(rpkm_pc), 
                                        c("ENTREZID","SYMBOL"), 
                                        "ENSEMBL")

genes_mapping <- as.data.frame(genes(Homo.sapiens, 
                                     filter = 
                                       list("GENEID" = entrez_mapping$ENTREZID)))
genes_mapping$GENEID = sapply(genes_mapping$GENEID, as.character)

chr21 <- inner_join(entrez_mapping, genes_mapping, by = c("ENTREZID" = "GENEID")) %>% 
   mutate(seqnames = as.character(seqnames)) %>% 
   filter(seqnames == "chr21")

chr21_uniq <- dplyr::group_by(chr21, ENSEMBL) %>% filter(row_number()==1) %>% ungroup()

```

## Make SummarizedExperiment

```{r}
library(SummarizedExperiment)
library(dplyr)
rpkm_chr21 <- SummarizedExperiment(assays = list(rpkm = as.matrix(rpkm_pc[chr21_uniq$ENSEMBL,2:57])), 
                     colData = filter(meta_data, EID %in% colnames(rpkm_pc)),
                     rowRanges = as(chr21_uniq,"GenomicRanges"))

```




