---
title: "Untitled"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE, autodep=TRUE)
#library(gChipseq)
library(chipVis)
library(TxDb.Hsapiens.BioMart.igis3.0)
library(plotly)
library(iHeatmapR)
BiocParallel::register(BiocParallel::MulticoreParam(4, progressbar = FALSE))
```

``` {r Load Data}

fi <- readRDS("/gne/research/workspace/schepa/Carroll_Data/chip_file_info.Rds")

org <- "human"
genome <- "GRCh38"

# Get scaling factors based on library size
sf <- get_scaling_factor(fi)[2,]/1000000

rpkmEset <- readRDS("/gne/research/workspace/schepa/Carroll_Data/GSE68358.rpkmEset.with_fdata.Rds")

tss_ranges <- with(fData(rpkmEset), GenomicRanges::GRanges(chr,
                                               IRanges::IRanges(start = ifelse(strand == "-",
                                                                               end,
                                                                               start),
                                                                width = 1),
                                               strand = strand,
                                               symbol = symbol,
                                               entrez = entrez))


```
  
 
```{r}
T47D_eset <- rpkmEset[,grep("T47D",pData(rpkmEset)$celltype)]
treat_groups = stringr::str_trim(sapply(stringr::str_split(pData(T47D_eset)$treatment,":"), 
                      function(x) x[[2]])) %>% gsub("+","_",., fixed= TRUE) %>% 
  gsub("_3hr","",.)

library(limma)
library(edgeR)

dge <- DGEList(counts = exprs(T47D_eset)) %>% calcNormFactors()
design <- model.matrix(~ 0 +treat_groups)
colnames(design) = gsub("treat_groups", "", colnames(design))
v <- voom(dge, design=design)
fit <- lmFit(v, design)
contrasts <- makeContrasts(E2_Progesterone-E2, 
                           E2_R5020-E2, 
                           E2_R5020-E2_Progesterone, levels = design)
fit2 <- contrasts.fit(fit, contrasts) %>% eBayes()
results_Progesterone <- topTable(fit2, coef = 1, adjust = "BH")
results_R5020 <- topTable(fit2, coef = 2, adjust = "BH")


results <- decideTests(fit2, p.value = 0.01, lfc = 1)
sig <- which(apply(results,1, function(x) sum(x!=0) > 0))

# T47D_exprs = log10(exprs(T47D_eset)+1)
# T47D_var = apply(T47D_exprs,1, function(x)
#                  
#                  sd, na.rm= TRUE)
# high_var = which(T47D_var > quantile(T47D_var,0.95,na.rm= TRUE))

rna_hm <- genomics_heatmap(v$E[sig,], col_groups = treat_groups,
            x = pData(T47D_eset)$title, y = fData(T47D_eset)$symbol[sig],
            name = "RNA-seq",cbg = colorbar_grid(x_spacing = 0.3, nrow = 2)) 

# rna_hm %>% plot_iHeatmap() %>% layout(margin = list(b = 250)) %>% export(file = "/gne/research/workspace/schepa/Carroll_Data/Figures/rna_hm.pdf")

```

  
#Get T47D Progesterone  
  
```{r MCF7_tss_cvg}
T47D = list(
  ER_ab = which(fi$source_name == "T47D_ER_Full_Media_3hr"),
  ER_ab_Pr_treat = which(fi$source_name == "T47D_ER_Progesterone_3hr"),
  ER_ab_R5020_treat = which(fi$source_name == "T47D_ER_R5020_3hr"),
  
  PR_ab  = which(fi$source_name == "T47D_PR_Full_Media_3hr"),
  PR_ab_Pr_treat = which(fi$source_name == "T47D_PR_Progesterone_3hr"),
  PR_ab_R5020_treat = which(fi$source_name == "T47D_PR_R5020_3hr"),
  
  p300_ab  = which(fi$source_name == "T47D_p300_Full_Media_3hr"),
  p300_ab_Pr_treat  = which(fi$source_name == "T47D_p300_Progesterone_3hr"),
  p300_ab_R5020_treat = which(fi$source_name == "T47D_p300_R5020_3hr")
  
)


# T47D = list(
#   T47D_ER_3hr_Vehicle  = which(fi$source_name == "T47D_ER_3hr_Vehicle"),
#   T47D_ER_3hr_E2 = which(fi$source_name == "T47D_ER_3hr_E2"),
#   T47D_ER_3hr_PG = which(fi$source_name == "T47D_ER_3hr_PG"),
#   T47D_ER_3hr_E2_PG = which(fi$source_name == "T47D_ER_3hr_E2+PG"),
#   
#   T47D_PR_3hr_Vehicle  = which(fi$source_name == "T47D_PR_3hr_Vehicle"),
#   T47D_PR_3hr_E2 = which(fi$source_name == "T47D_PR_3hr_E2"),
#   T47D_PR_3hr_PG = which(fi$source_name == "T47D_PR_3hr_PG"),
#   T47D_PR_3hr_E2_PG = which(fi$source_name == "T47D_PR_3hr_E2+PG")
#   
# )

tss_cvg_mats <- lapply(T47D, function(x){
  tmp <- make_coverage_matrix(inputs = fi$File.bam[x],
                                  ranges = tss_ranges[sig],
                                  binsize = 100,
                                  up = 5000,
                                  down = 5000)
  out <- Reduce("+", tmp) / length(tmp)
  return(out)
})

promoter_ranges = GenomicRanges::promoters(tss_ranges,
                                                 up = 5000,
                                                 down = 5000)

er_promoter_counts <- simplify2array(
  BiocParallel::bplapply(fi$File.bam[unlist(T47D[1:3])],
                         bamsignals::bamCount,
                         promoter_ranges[sig])) %>% 
  scale(center = FALSE, scale = sf[unlist(T47D[1:3])])

pr_promoter_counts <- simplify2array(
  BiocParallel::bplapply(fi$File.bam[unlist(T47D[4:6])],
                         bamsignals::bamCount,
                         promoter_ranges[sig])) %>% 
  scale(center = FALSE, scale = sf[unlist(T47D[4:6])])

p300_promoter_counts <- simplify2array(
  BiocParallel::bplapply(fi$File.bam[unlist(T47D[7:9])],
                         bamsignals::bamCount,
                         promoter_ranges[sig])) %>% 
  scale(center = FALSE, scale = sf[unlist(T47D[7:9])])


colnames(er_promoter_counts) <- unlist(fi$source_name[unlist(T47D[1:3])], use.names= FALSE)
er_chip_condition <- unlist(fi$condition[unlist(T47D[1:3])], use.names= FALSE)


colnames(pr_promoter_counts) <- unlist(fi$source_name[unlist(T47D[4:6])], use.names= FALSE)
pr_chip_condition <- unlist(fi$condition[unlist(T47D[4:6])], use.names= FALSE)

colnames(p300_promoter_counts) <- unlist(fi$source_name[unlist(T47D[7:9])], use.names= FALSE)
p300_chip_condition <- unlist(fi$condition[unlist(T47D[7:9])], use.names= FALSE)



rna_plus_er_tss_hm <- rna_hm %>% 
  add_multi_coverage_heatmap(tss_cvg_mats[1:3],
                             colorscale = continuous_colorscale("Reds"))
  
rna_plus_er_tss_hm %>%
  plot_iHeatmap() %>% export(file = "/gne/research/workspace/schepa/Carroll_Data/Figures/rna_plus_er_tss.png")
  
  
er_chip_hm <- genomics_heatmap(er_promoter_counts, col_groups = er_chip_condition,
            y = fData(T47D_eset)$symbol[sig],
            x_labels = NULL, name = "ChIP-seq") 


rna_plus_chip_hm <- rna_hm %>% add_genomics_heatmap(er_promoter_counts,
                                col_groups = er_chip_condition,
                                col_groups_palette = "Paired",
                                colorscale = continuous_colorscale("Reds"),
                                name = "ER ChIP",
                                x_title = "ER",
                                size = 0.8) %>% 
  add_genomics_heatmap(pr_promoter_counts,
                                col_groups = pr_chip_condition,
                       colorscale = continuous_colorscale("Reds"),
                                name = "PR ChIP",
                       col_groups_palette = "Paired",
                       show_col_groups_colorbar  = FALSE,
                                x_title = "PR",
                                size = 0.8) %>% 
  add_genomics_heatmap(p300_promoter_counts,
                                col_groups = p300_chip_condition,
                                name = "P300 ChIP",
                       colorscale = continuous_colorscale("Reds"),
                       col_groups_palette = "Paired",
                       show_col_groups_colorbar = FALSE,
                                x_title = "p300",
                                size = 0.8)


rna_plus_chip_hm %>%
  plot_iHeatmap()  %>% export(file = "/gne/research/workspace/schepa/Carroll_Data/Figures/rna_plus_chip.png")
 

#COLLAPSE CHIP

er_promoter_counts_collapsed <- sapply(unique(er_chip_condition),
                                      function(x){
                                        tmp <- which(er_chip_condition == x)
                                        apply(er_promoter_counts[,tmp], 1, sum, na.rm = TRUE)
                                      })

pr_promoter_counts_collapsed <- sapply(unique(pr_chip_condition),
                                      function(x){
                                        tmp <- which(pr_chip_condition == x)
                                        apply(pr_promoter_counts[,tmp], 1, sum, na.rm = TRUE)
                                      })


p300_promoter_counts_collapsed <- sapply(unique(p300_chip_condition),
                                      function(x){
                                        tmp <- which(p300_chip_condition == x)
                                        apply(p300_promoter_counts[,tmp], 1, sum, na.rm = TRUE)
                                      })

rna_chip_collapsed_hm <- rna_hm %>% add_genomics_heatmap(er_promoter_counts_collapsed,
                              col_groups = c("Full Media", "Progesterone",
                                             "R5020"),
                              col_groups_palette = "Paired",
                              colorscale = continuous_colorscale("Reds"),
                              name = "ER ChIP",
                              size = 0.3,
                              x_title = "ER") %>%
  add_genomics_heatmap(pr_promoter_counts_collapsed,
                              col_groups = c("Full Media", "Progesterone",
                                             "R5020"),
                              col_groups_palette = "Paired",
                       colorscale = continuous_colorscale("Reds"),
                      show_col_groups_colorbar = FALSE,
                              name = "PR ChIP",
                              size = 0.3,
                              x_title = "PR")%>%
  add_genomics_heatmap(p300_promoter_counts_collapsed,
                              col_groups = c("Full Media", "Progesterone",
                                             "R5020"),
                              col_groups_palette = "Paired",
                       colorscale = continuous_colorscale("Reds"),
                      show_col_groups_colorbar = FALSE,
                              name = "p300 ChIP",
                              size = 0.3,
                              x_title = "p300")

rna_chip_collapsed_hm %>%
  plot_iHeatmap()  %>% export(file = "/gne/research/workspace/schepa/Carroll_Data/Figures/rna_plus_chip_collapsed.png")
 


# tr <- transcriptsBy(TxDb.Hsapiens.BioMart.igis, by = "gene") %>% unlist()
# tr$entrez <- stringr::str_extract(names(tr),"(?<=:)(.*)")
# tr$symbol <- annotate::getSYMBOL(tr$entrez, data='org.Hs.eg')
# names(tr) = NULL
# tr <- resize(tr, fix = "start", width = 1)
# 
# tss_cvg_mats2 <- lapply(T47D, function(x){
#   tmp <- make_coverage_matrix(inputs = fi$File.bam[x],
#                                   ranges = tr[which(tr$entrez %in% tss_ranges$entrez[high_var])],
#                                   binsize = 25,
#                                   up = 1000,
#                                   down = 1000)
#   out <- Reduce("+", tmp) / length(tmp)
#   return(out)
# })

# 
# tss <- gChipseq::tssFromTxdb(txdb = TxDb.Hsapiens.BioMart.igis)
# #unique_tss <- unique(tss) #Remove same positions
# 
# peaks <- lapply( fi$File.macs[unlist(T47D)], readMacsPeaks, fc=5, minTags=10, fdr=0.01)
# peaks <- peaks[!sapply(peaks, is.null)]
# 
# merged_peaks <- reduce(do.call(c, peaks))
# 
# tss_in_peaks <- subsetByOverlaps(tss_ranges, merged_peaks, maxgap = 0)
# 
# tss_cvg_mats <- lapply(T47D, function(x){
#   tmp <- make_coverage_matrix(inputs = fi$File.bam[x],
#                                   ranges = tss_ranges[high_var],
#                                   binsize = 25,
#                                   up = 1000,
#                                   down = 1000)
#   out <- Reduce("+", tmp) / length(tmp)
#   return(out)
# })

```



```{r}
rna_hm %>% add_coverage_heatmap(tss_cvg_mats[[2]])

new_single_coverage_heatmap(tss_cvg_mats[[1]], row_order = "signal", y = tss_ranges$symbol[sig])
```

```{r}
T47D_ER_tss_cvg_mats = tss_cvg_mats[1:3]
names(T47D_ER_tss_cvg_mats) = c("Control","Pr","Syn. Pr")
multi_coverage_heatmap(T47D_ER_tss_cvg_mats, row_order = "kmeans", y = tss_in_peaks$symbol, k = 3)
```

```{r}
MCF7_PR_tss_cvg_mats = tss_cvg_mats[4:6]
names(MCF7_PR_tss_cvg_mats) = c("Control","Pr","Syn. Pr")
multi_coverage_heatmap(MCF7_PR_tss_cvg_mats, row_order = "kmeans", y = tss_in_peaks$symbol, k = 3)
```


```{r}
peaks <- lapply( fi$File.macs[unlist(T47D)], readMacsPeaks, fc=5, minTags=10, fdr=0.01)
peaks <- peaks[!sapply(peaks, is.null)]

merged_peaks <- lapply(T47D,
                       function(x){
                         peaks <- lapply( fi$File.macs[x], readMacsPeaks, fc=5, minTags=10, fdr=0.01)
                         peaks <- peaks[!sapply(peaks, is.null)]
                         reduce(do.call(c, peaks), min.gapwidth = 500)
                         })
                    

rp_scores <- sapply(merged_peaks, compute_regulatory_potential, tss_ranges)

rna_rp_hm <- rna_hm %>% add_genomics_heatmap(rp_scores[sig,1:3],
                              col_groups = c("Full Media", "Progesterone",
                                             "R5020"),
                              col_groups_palette = "Paired",
                              colorscale = continuous_colorscale("Reds"),
                              name = "ER<br>Regulatory<br>Potential",
                              size = 0.3,
                              x_title = "ER") %>%
  add_genomics_heatmap(rp_scores[sig,4:6],
                              col_groups = c("Full Media", "Progesterone",
                                             "R5020"),
                              col_groups_palette = "Paired",
                       colorscale = continuous_colorscale("Reds"),
                      show_col_groups_colorbar = FALSE,
                              name = "PR<br>Regulatory<br>Potential",
                              size = 0.3,
                              x_title = "PR")%>%
  add_genomics_heatmap(rp_scores[sig,7:9],
                              col_groups = c("Full Media", "Progesterone",
                                             "R5020"),
                              col_groups_palette = "Paired",
                       colorscale = continuous_colorscale("Reds"),
                      show_col_groups_colorbar = FALSE,
                              name = "p300<br>Regulatory<br>Potential",
                              size = 0.3,
                              x_title = "p300")

rna_rp_hm %>%
  plot_iHeatmap()  %>% export(file = "/gne/research/workspace/schepa/Carroll_Data/Figures/rna_plus_rp.png")
 


rna_hm %>% add_genomics_heatmap(rp_scores[sig,],scale = "none",
                              col_groups = rep(c("ER","PR","p300"), each = 3),
                              name = "Regulatory<br>Potential") 

#%>%
#  plot_iHeatmap() %>% layout(margin = list(b = 250)) %>% export(file = #"/gne/research/workspace/schepa/Carroll_Data/Figures/rna_plus_regulatory_potential.png")




er_progesterone_peaks_cvg_mats <- lapply(T47D, function(x){
  tmp <- make_coverage_matrix(inputs = fi$File.bam[x],
                                  ranges = merged_peaks[[2]][1:5000],
                                  binsize = 50,
                                  up = 1000,
                                  down = 1000)
  out <- Reduce("+", tmp) / length(tmp)
  return(out)
})
#merged_peaks <- reduce(do.call(c, peaks))

T47D_scale_factors = sapply(T47D, function(x) mean(sf[x]))

```

```{r}
ag1 = aggregate_profile_plot(er_progesterone_peaks_cvg_mats[1:3],xlab = "",
                            ylab = "ER ChIP-Signal")
ag2 = aggregate_profile_plot(er_progesterone_peaks_cvg_mats[4:6],xlab = "Position relative to ER Peaks<br> in T47D + Progesterone",
                            ylab = "PR ChIP-Signal")

ag1 %>% export(file = "~/workspace//Carroll_Data/Figures/aggregate_profiles1.pdf")
# ag2 %>% export(file = "/gne/research/workspace/schepa/Carroll_Data/Figures/aggregate_profiles2.pdf")


```

```{r}
mchm <- multi_coverage_heatmap(er_progesterone_peaks_cvg_mats[1:3], row_order = "kmeans", k = 3, cluster_by = "first")

# mchm %>% plot_iHeatmap %>% layout(margin = list(b = 250)) %>% export(file = "/gne/research/workspace/schepa/Carroll_Data/Figures/multi_coverage.pdf")

```


