---
title: "Untitled"
author: "Alicia Schep"
date: "8/29/2016"
output: html_document
---

<style type="text/css">

body, td {
   font-size: 14px;
}
code.r{
  font-size: 16px;
}
pre {
  font-size: 20px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

```{r}
multi_coverage_heatmap(ER_cvg_mats, 
                       row_order = "kmeans", k = 2, 
                      name = "ER<br>Coverage",
                       signal_name = "Er Avg.") %>%
  add_multi_coverage_heatmap(PR_cvg_mats,
                             name = "PR<br>Coverage", 
                             signal_name = "Pr Avg.")
```

```{r}
genomics_heatmap(expression_matrix, 
                 col_groups = col_group_names, 
                 row_groups_name = "Gene<br>Clusters",
                 col_groups_name = "Hormone<br>Treatment",
                 row_k = 2,
                 x = sample_names, 
                 y = gene_names,
                 name = "Relative<br>RNA<br>Expression")
```

```{r}
rna_heatmap %>% 
  add_genomics_heatmap(er_promoter_counts_collapsed,
                       col_groups = c("Full Media", "P4",
                                      "R5020"),
                       col_groups_palette = "Paired",
                       col_groups_name = "Hormone<br>Treatment",
                       colorscale = continuous_colorscale("Reds"),
                       name = "ER ChIP",
                       size = 0.3,
                       x_title = "ER", 
                       scale = "none") %>% ...
```


