---
title: "Multiple Chip-Seq Heatmap Example"
author: "Alicia Schep"
date: "7/8/2016"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
require(gChipseq)
require(TxDb.Mmusculus.BioMart.igis)
require(biomaRt)
require(rtracklayer)
require(Gviz)
options(ucscChromosomeNames=FALSE)
BiocParallel::register(BiocParallel::MulticoreParam(4, progressbar = FALSE))

```

## Reading in the Data

Example of reading in data

```{r inputs, warnings = FALSE, message = FALSE, results='hide'}


file.sample <- "~/workspace/BAP1_Data/BAP1_june_2016_samples.txt"
file.pair <- "~/workspace/BAP1_Data/BAP1_june_2016_pairs.txt"

samples <- read.table(file.sample,as.is=TRUE,header=TRUE)
samples_exp <- expandSampleTable(samples)

pairs <- read.table(file.pair,as.is=TRUE,header=TRUE)
pairs_exp <- expandPairedTable(pairs)

tss <- tssFromTxdb(txdb = TxDb.Mmusculus.BioMart.igis)
unique_tss <- unique(tss) #Remove same positions

peaks <- lapply( pairs$File.macs, readMacsPeaks, fc=5, minTags=10, fdr=0.1)
peaks <- peaks[!sapply(peaks, is.null)]

merged_peaks <- reduce(do.call(c, peaks))

tss_in_peaks <- subsetByOverlaps(unique_tss, merged_peaks, maxgap = 1000)

```

## Prepping Data
```{r bams, warnings = FALSE, message = FALSE, results='hide'}
source('/gnet/is7/workspace/schepa/chipVis/R/coverage_matrix.R')

bam_files <- samples_exp$File.bam
names(bam_files) <- samples$Genotype

cvg_files <- samples_exp$File.bw
names(cvg_files) <- samples$Genotype

 cvg_mats <- make_coverage_matrix(inputs = bam_files,
                                  ranges = tss_in_peaks,
                                  binsize = 50,
                                  up = 2500,
                                  down = 2500)

```


## Embedded Application


```{r shiny, echo=FALSE, cache = FALSE, message = FALSE}

source('/gnet/is7/workspace/schepa/chipVis/R/multi_coverage_shiny.R')
source('/gnet/is7/workspace/schepa/chipVis/R/single_coverage_heatmap.R')
source('/gnet/is7/workspace/schepa/chipVis/R/trackview_functions.R')


multi_coverage_plot(inputs = cvg_mats,#bam_files, 
                    regions = tss_in_peaks, 
                    region_names = tss_in_peaks$names, 
                    up = 2500, 
                    down = 2500,
                    cvg_files = cvg_files)

```



