---
title: "Coverage Matrix Test"
author: "Alicia Schep"
date: "7/8/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## Reading in Sample Table

```{r samples, message = FALSE, warning=FALSE, results='hide'}
library(gChipseq)
library(TxDb.Mmusculus.BioMart.igis)

file.sample <- "~/workspace/BAP1_Data/BAP1_june_2016_samples.txt"
file.pair <- "~/workspace/BAP1_Data/BAP1_june_2016_pairs.txt"

samples <- read.table(file.sample,as.is=TRUE,header=TRUE)
samples <- expandSampleTable(samples)

```

## Reading in TSS

```{r tss, message = FALSE, warning=FALSE, results='hide'}

tss <- tssFromTxdb(txdb = TxDb.Mmusculus.BioMart.igis)
unique_tss <- unique(tss) #Remove same positions

```

## Prepping Data
```{r files, cache = FALSE, message = FALSE, warning=FALSE, results='hide'}
cvg_files <- samples$File.bw
names(cvg_files) <- samples$Sample.Name

bam_files <- samples$File.bam
names(bam_files) <- samples$Sample.Name

rdata_files <- samples$File.cvg
names(rdata_files) <- samples$Sample.Name

rle_obj <- lapply(rdata_files[1:4], function(x){
  loader <- load(x)
  out <- get(loader)
  return(out)
})

```

## Compare speed with 100 ranges

```{r time100, message = FALSE, warning=FALSE, results='hide'}
BiocParallel::register(BiocParallel::MulticoreParam(4, progressbar = TRUE))
source("~/workspace/chipVis/R/coverage_matrix.R")

time100 <- microbenchmark::microbenchmark(bw = make_coverage_matrix(inputs = cvg_files[1:4],
                                              ranges = unique_tss[1:100],
                                              binsize = 50,
                                              up = 2500,
                                              down = 2500), 
                    bam = make_coverage_matrix(inputs = bam_files[1:4],
                                               ranges = unique_tss[1:100],
                                               binsize = 50,
                                               up = 2500,
                                               down = 2500), 
                    rdata =  make_coverage_matrix(inputs = rdata_files[1:4],
                                                  ranges = unique_tss[1:100],
                                                  binsize = 50,
                                                  up = 2500,
                                                  down = 2500),
                    rle =  make_coverage_matrix(inputs = rle_obj[1:4],
                                                  ranges = unique_tss[1:100],
                                                  binsize = 50,
                                                  up = 2500,
                                                  down = 2500),times = 5)


```

```{r plot_time100, echo = FALSE}
print(time100 )
boxplot(time100,time ='s' )
```


## Compare speed with 1000 ranges

```{r time1000, message = FALSE, warning=FALSE, results='hide'}
time1000 <- microbenchmark::microbenchmark(bw = make_coverage_matrix(inputs = cvg_files[1:4],
                                              ranges = unique_tss[1:1000],
                                              binsize = 50,
                                              up = 2500,
                                              down = 2500), 
                    bam = make_coverage_matrix(inputs = bam_files[1:4],
                                               ranges = unique_tss[1:1000],
                                               binsize = 50,
                                               up = 2500,
                                               down = 2500),
                    rle =  make_coverage_matrix(inputs = rle_obj[1:4],
                                                  ranges = unique_tss[1:1000],
                                                  binsize = 50,
                                                  up = 2500,
                                                  down = 2500),times = 5)


```

```{r plot_time1000, echo = FALSE}
print(time1000 )
boxplot(time1000,time="s" )
```


## Compare speed with 5000 ranges

```{r time5000, message = FALSE, warning=FALSE, results='hide'}
time5000  <- microbenchmark::microbenchmark(bw = make_coverage_matrix(inputs = cvg_files[1:4],
                                              ranges = unique_tss[1:5000],
                                              binsize = 50,
                                              up = 2500,
                                              down = 2500), 
                    bam = make_coverage_matrix(inputs = bam_files[1:4],
                                               ranges = unique_tss[1:5000],
                                               binsize = 50,
                                               up = 2500,
                                               down = 2500),
                    rle =  make_coverage_matrix(inputs = rle_obj[1:4],
                                                  ranges = unique_tss[1:5000],
                                                  binsize = 50,
                                                  up = 2500,
                                                  down = 2500), times = 5)


```

```{r plot_time5000, echo = FALSE}
print(time5000)
boxplot(time5000,time='s' )
```

## Similarity Between Results

```{r compare, message = FALSE, warning=FALSE, results='hide'}
bw = make_coverage_matrix(inputs = cvg_files[1:4],
                                              ranges = unique_tss[c(1,870)],
                                              binsize = 50,
                                              up = 2500,
                                              down = 2500)
bam = make_coverage_matrix(inputs = bam_files[1:4],
                                               ranges = unique_tss[c(1,870)],
                                               binsize = 50,
                                               up = 2500,
                                               down = 2500)

rdata =  make_coverage_matrix(inputs = rdata_files[1:4],
                                                  ranges = unique_tss[c(1,870)],
                                                  binsize = 50,
                                                  up = 2500,
                                                  down = 2500)

rle =  make_coverage_matrix(inputs = rle_obj[1:4],
                            ranges = unique_tss[c(1,870)],
                            binsize = 50,
                            up = 2500,
                            down = 2500)


```

## Test ranges

```{r testranges, echo = FALSE}
print(unique_tss[c(1,870)])

```

## + strand

```{r compare_plot_1, echo = FALSE, fig.height= 8}
par(mfrow = c(4,1))
plot(colnames(bw[[1]]),bw[[1]][1,], xlab = "position",ylab="coverage",main = "bigwig", type = 'l')
plot(colnames(bw[[1]]),bam[[1]][1,], xlab = "position",ylab="coverage",main = "bam", type = 'l')
plot(colnames(bw[[1]]),rdata[[1]][1,], xlab = "position",ylab="coverage",main = "rdata", type = 'l')
plot(colnames(bw[[1]]),rle[[1]][1,], xlab = "position",ylab="coverage",main = "rle", type = 'l')

```

## - strand

```{r compare_plot_2, echo = FALSE, fig.height= 8}
par(mfrow = c(4,1))
plot(colnames(bw[[1]]),bw[[1]][2,], xlab = "position",ylab="coverage",main = "bigwig", type = 'l')
plot(colnames(bw[[1]]),bam[[1]][2,], xlab = "position",ylab="coverage",main = "bam", type = 'l')
plot(colnames(bw[[1]]),rdata[[1]][2,], xlab = "position",ylab="coverage",main = "rdata", type = 'l')
plot(colnames(bw[[1]]),rle[[1]][2,], xlab = "position",ylab="coverage",main = "rle", type = 'l')

```





